# Generated by Django 5.0 on 2023-12-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
                ("nombres", models.CharField(max_length=64)),
                ("apellidos", models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="anio_publicacion",
            new_name="anio_publicacion",
        ),
    ]
