# Generated by Django 5.0 on 2023-12-12 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0002_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nombres",
        ),
    ]
