# Generated by Django 5.0 on 2023-12-12 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0003_remove_usuario_apellidos_remove_usuario_nombres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="password",
            new_name="contrasena",
        ),
    ]
